test on old motorola dev

diff --git a/bin/adb_connect b/bin/adb_connect
--- a/bin/adb_connect
+++ b/bin/adb_connect
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+# NOTES:
+#
 # Enable developer mode by tapping build number 8 times.
 # 
 # Go to Developer Options , and enable
@@ -21,4 +23,14 @@
 # 
 # Plug phone in with power cable, to disable sleeping while charging.
 
-adb connect 192.168.1.243:5555
+if [ "$1" = "" ]; then
+  echo "ERROR: name or ipaddr required"
+  exit 1
+fi
+
+adb kill-server
+adb start-server
+adb connect $1
+
+echo 
+adb devices
diff --git a/bin/ezput b/bin/ezput
--- a/bin/ezput
+++ b/bin/ezput
@@ -6,16 +6,26 @@
 # - with args, the files specified in the args are transferred to the Android device
 #
 # - examples:
-#   - ezput                    # sends git tracked files from this dir to android
-#   - ezput apps/layout        # sends just the apps/layout file to android
-#   - ezput apps/lib/lib.[ch]  # sends apps/lib/lib.[ch] to android
+#   - ezput dev password                    # sends git tracked files from this dir to android dev
+#   - ezput dev password apps/layout        # sends just the apps/layout file to android dev
+#   - ezput dev password apps/lib/lib.[ch]  # sends apps/lib/lib.[ch] to android dev
 
 # verify current dir is in a git repo
 top=$(git rev-parse --show-toplevel)
 if [ $? -ne 0 ]; then
-    echo "ERROR: not in git repo"
-    exit 1
+  echo "ERROR: not in git repo"
+  exit 1
 fi
+
+# verify dev and password args are provided
+if [ $# -lt 2 ]; then
+  echo "ERROR: dev and password required"
+  exit 1
+fi
+dev=$1
+shift
+password=$1
+shift
 
 # verify parent directory is 'apps' or 'svcs'
 parent_dir=$(basename $(dirname $PWD))
@@ -43,9 +53,7 @@ for i in $*; do
   specified_files="$specified_files $i"
 done
 
-# copy to Android:
-# - git tracked files that are in the app/svc dir
-# - more files which the caller has requested on the cmdline
+# copy files to Android dev
 cd ../..
 if [ "$specified_files" != "" ]; then
   files="$specified_files"
@@ -56,14 +64,29 @@ else
     exit 1
   fi
 fi
+
 tar -cf /tmp/ezput.tar  $files
 if [ $? -ne 0 ]; then
+  rm -f /tmp/ezput.tar
   exit 1
 fi
-echo "Creating files on Android device ..."
-ezsh put /tmp/ezput.tar 
-ezsh tar -xvf ezput.tar
-ezsh rm -f ezput.tar
-rm -f /tmp/ezput.tar
 
+echo "Creating files on Android device ..."
+ezsh $dev $password put /tmp/ezput.tar 
+if [ $? -ne 0 ]; then 
+  rm -f /tmp/ezput.tar
+  exit 1
+fi
+ezsh $dev $password tar -xvf ezput.tar
+if [ $? -ne 0 ]; then 
+  rm -f /tmp/ezput.tar
+  exit 1
+fi
+ezsh $dev $password rm -f ezput.tar
+if [ $? -ne 0 ]; then 
+  rm -f /tmp/ezput.tar
+  exit 1
+fi
+
+rm -f /tmp/ezput.tar
 exit 0
