update scripts

diff --git a/bin/ezget b/bin/ezget
--- a/bin/ezget
+++ b/bin/ezget
@@ -1,7 +1,61 @@
 #!/bin/bash
 
-# xxx usage comments
-# - only options,  no other args
+function usage()
+{
+cat << EOF
+This script copies files from the Android device to the files hierarchy.
+EzApp must be running on the Android device, and have DeveloperMode enabled.
+  
+This script must be run from a directory in the files hierarchy.
+
+Options:
+  -h             : display usage and exit
+  -d <dev>       : dev name (such as from /etc/hosts), or dev ipaddr
+  -p <password>  : ezApp devel mode password
+Environment variables EZAPP_DEVICE and EZAPP_PASSWD may be used instead
+of the -d and -p options.
+
+Usage examples:
+  # copy all files from Android ezApp Morse dir to devel PC
+  cd files/apps/Morse
+  ezget
+  #
+  # copy all files from Android files hierarchy to devel PC
+  cd files
+  ezget
+EOF
+} 
+
+# #############  MAIN  ################
+
+# process options 
+# -h             : display usage
+# -d <dev>       : dev name (such as from /etc/hosts), or dev ipaddr
+# -p <password>  : devel password
+while true; do
+    if [ "$1" = "-h" ]; then
+        usage
+        exit 0
+    elif [ "$1" = "-d" ]; then
+        dev=$2
+        shift 2
+    elif [ "$1" = "-p" ]; then
+        password=$2
+        shift 2
+    elif [[ "$1" == "-"* ]]; then
+        echo "ERROR: invalid option $1"
+        exit 1
+    else
+        break
+    fi
+done
+
+# no additional args are allowed by ezget
+if [ $# -ne 0 ]; then
+    echo "ERROR: Ezget only supports copying files to the current directory."
+    echo "ERROR: Args are not allowed."
+    exit 1
+fi
 
 # determine the top of the files directory tree,
 # this works if CWD is one of the following directories, for example:
@@ -9,51 +63,33 @@
 # - /path_to_files/files/apps
 # - /path_to_files/files/apps/Template
 if [ $(basename "$PWD") = files ]; then
-  files_dir=$PWD
+    files_dir=$PWD
 elif [ $(basename "$(dirname "$PWD")") = files ]; then
-  files_dir=$(dirname $PWD)
+    files_dir=$(dirname $PWD)
 elif [ $(basename "$(dirname "$(dirname "$PWD")")") = files ]; then
-  files_dir=$(dirname $PWD)
-  files_dir=$(dirname $files_dir)
+    files_dir=$(dirname $PWD)
+    files_dir=$(dirname $files_dir)
 else
-  echo "ERROR: $PWD must be in files directory tree"
-  exit 1
+    echo "ERROR: $PWD must be in files directory tree"
+    exit 1
 fi
 
 # determine Android directory from which the files will be copied
 android_dir=$(realpath --relative-base $files_dir $PWD)
 if [ "$android_dir" = "" ]; then
-  echo "ERROR: failed to determine android_dir"
-  exit 1
+    echo "ERROR: failed to determine android_dir"
+    exit 1
 fi
 
 # get device and developer password from optional env vars
 dev=$EZAPP_DEVICE
 password=$EZAPP_PASSWD
 
-# process options 
-# -d <dev>       : dev name (such as from /etc/hosts), or dev ipaddr
-# -p <password>  : devel password
-while true; do
-  if [ "$1" = "-d" ]; then
-    dev=$2
-    shift 2
-  elif [ "$1" = "-p" ]; then
-    password=$2
-    shift 2
-  elif [[ "$1" == "-"* ]]; then
-    echo "ERROR: invalid option $1"
-    exit 1
-  else
-    break
-  fi
-done
-
 # verify dev and password have been provided,
 # either from env vars or the -d and -p options
 if [ "$dev" = "" -o "$password" = "" ]; then
-  echo "ERROR: device and password are required"
-  exit 1
+    echo "ERROR: device and password are required"
+    exit 1
 fi
 
 # print message
@@ -61,28 +97,28 @@ echo "INFO: transferring files from Android device to devel PC"
 
 # create ezget.tar on Android device
 if [ "$android_dir" = "." ]; then
-  ezsh -d $dev -p $password -q "tar -cf ezget.tar $exclude apps svcs params"
+    ezsh -d $dev -p $password -q "tar -cf ezget.tar apps svcs params"
 else 
-  ezsh -d $dev -p $password -q "tar -cf ezget.tar $exclude $android_dir"
+    ezsh -d $dev -p $password -q "tar -cf ezget.tar $android_dir"
 fi
 if [ $? -ne 0 ]; then 
-  echo "ERROR: failed to create ezget.tar on Android device"
-  exit 1
+    echo "ERROR: failed to create ezget.tar on Android device"
+    exit 1
 fi
 
 # copy ezget.tar from Android device to /tmp
 ezsh -d $dev -p $password -q "get ezget.tar /tmp"
 if [ $? -ne 0 ]; then 
-  echo "ERROR: failed to copy ezget.tar from Android device to devel PC"
-  exit 1
+    echo "ERROR: failed to copy ezget.tar from Android device to devel PC"
+    exit 1
 fi
 
 # extract ezget.tar on devel PC
 cd $files_dir
 tar -xvf /tmp/ezget.tar
 if [ $? -ne 0 ]; then 
-  echo "ERROR: failed to extract ezget.tar on devel PC"
-  exit 1
+    echo "ERROR: failed to extract ezget.tar on devel PC"
+    exit 1
 fi
 
 # cleanup
diff --git a/bin/ezput b/bin/ezput
--- a/bin/ezput
+++ b/bin/ezput
@@ -1,35 +1,86 @@
 #!/bin/bash
 
-# xxx add -h option, also to ezget
+function usage()
+{
+cat << EOF
+This script copies files to the Android device.
+EzApp must be running on the Android device, and have DeveloperMode enabled.
 
-# xxx comments
-# ezput
-# ezput .
-# ezput . ../lib ../layout
-# ezput -f .
+This script must be run from a directory in the files hierarchy.
+
+Options:
+  -h             : display usage and exit
+  -d <dev>       : dev name (such as from /etc/hosts), or dev ipaddr
+  -p <password>  : ezApp devel mode password
+  -f             : force xfer of data files; data files are not normally copied
+Environment variables EZAPP_DEVICE and EZAPP_PASSWD may be used instead
+of the -d and -p options.
+
+Usage examples:
+  # in these examples, the data files are not included in the files copied to Android
+  #
+  # copy all files in MyNewApp and lib dirs, and the apps/layout file to Android
+  cd files/apps/MyNewApp
+  ezput . ../lib ../layput 
+  #
+  # copy all files in Morse dir to Adnroid
+  cd files/apps/Morse
+  ezput
+  #
+  # copy all of the files hierarchy to Android
+  cd files
+  ezput
+EOF
+}
 
 function okay_to_xfer()
 {
-  if [ "$force" = yes ]; then
-    return 0
-  fi
+    if [ "$force" = yes ]; then
+        return 0
+    fi
 
-  if [[ "$1" == *".png" || \
-        "$1" == *".json" || \
-        "$1" == *".dat" || \
-        "$1" == *".mp3" || \
-        "$1" == *"params" || \
-        "$1" == *"FreeMonoBold.ttf" || \
-        "$1" == *"credits" || \
-        "$1" == *"licenses" ]]; \
-  then
-    return 1
-  else
-    return 0
-  fi
+    if [[ "$1" == *".png" || \
+          "$1" == *".json" || \
+          "$1" == *".dat" || \
+          "$1" == *".mp3" || \
+          "$1" == *"params" || \
+          "$1" == *"FreeMonoBold.ttf" || \
+          "$1" == *"credits" || \
+          "$1" == *"licenses" ]]; \
+    then
+        return 1
+    else
+        return 0
+    fi
 }
 
 # #############  MAIN  ################
+
+# process options 
+# -h             : display usage
+# -d <dev>       : dev name (such as from /etc/hosts), or dev ipaddr
+# -p <password>  : devel password
+# -f             : force xfer of data files
+while true; do
+    if [ "$1" = "-h" ]; then
+        usage
+        exit 0
+    elif [ "$1" = "-d" ]; then
+        dev=$2
+        shift 2
+    elif [ "$1" = "-p" ]; then
+        password=$2
+        shift 2
+    elif [ "$1" = "-f" ]; then
+        force=yes
+        shift 1
+    elif [[ "$1" == "-"* ]]; then
+        echo "ERROR: invalid option $1"
+        exit 1
+    else
+        break
+    fi
+done
 
 # determine the top of the files directory tree,
 # this works if CWD is one of the following directories, for example:
@@ -37,53 +88,31 @@ function okay_to_xfer()
 # - /path_to_files/files/apps
 # - /path_to_files/files/apps/Template
 if [ $(basename "$PWD") = files ]; then
-  files_dir=$PWD
+    files_dir=$PWD
 elif [ $(basename "$(dirname "$PWD")") = files ]; then
-  files_dir=$(dirname $PWD)
+    files_dir=$(dirname $PWD)
 elif [ $(basename "$(dirname "$(dirname "$PWD")")") = files ]; then
-  files_dir=$(dirname $PWD)
-  files_dir=$(dirname $files_dir)
+    files_dir=$(dirname $PWD)
+    files_dir=$(dirname $files_dir)
 else
-  echo "ERROR: $PWD must be in files directory tree"
-  exit 1
+    echo "ERROR: $PWD must be in files directory tree"
+    exit 1
 fi
 
 # get device and developer password from optional env vars
 dev=$EZAPP_DEVICE
 password=$EZAPP_PASSWD
 
-# process options 
-# -d <dev>       : dev name (such as from /etc/hosts), or dev ipaddr
-# -p <password>  : devel password
-# -f             : force xfer of data files
-while true; do
-  if [ "$1" = "-d" ]; then
-    dev=$2
-    shift 2
-  elif [ "$1" = "-p" ]; then
-    password=$2
-    shift 2
-  elif [ "$1" = "-f" ]; then
-    force=yes
-    shift 1
-  elif [[ "$1" == "-"* ]]; then
-    echo "ERROR: invalid option $1"
-    exit 1
-  else
-    break
-  fi
-done
-
 # verify dev and password have been provided,
 # either from env vars or the -d and -p options
 if [ "$dev" = "" -o "$password" = "" ]; then
-  echo "ERROR: device and password are required"
-  exit 1
+    echo "ERROR: device and password are required"
+    exit 1
 fi
 
 # if no args then default to transferring the current directory
 if [ $# -eq 0 ]; then
-  set -- "."
+    set -- "."
 fi
 
 # print message
@@ -92,8 +121,8 @@ echo "INFO: transferring files from devel PC to Android device"
 # find candidtate files to xfer
 find_output=$(find $* ! -type d 2>/dev/null)
 if [ $? -ne 0 ]; then
-  echo "ERROR: failed to create files list"
-  exit 1
+    echo "ERROR: failed to create files list"
+    exit 1
 fi
 
 # loop over candidate file
@@ -102,59 +131,59 @@ fi
 # - get the real path of the file, relative to the files_dir
 # - add the real path to list of files that will be xfered
 for fn in $find_output; do
-  okay_to_xfer $fn
-  if [ $? -ne 0 ]; then
-    echo "SKIPPING: $fn"
-    skipped=yes
-    continue
-  fi
+    okay_to_xfer $fn
+    if [ $? -ne 0 ]; then
+        echo "SKIPPING: $fn"
+        skipped=yes
+        continue
+    fi
 
-  real=$(realpath -s --relative-base $files_dir "$fn")
-  if [[ "$real" == "."* || "$real" == ".."* || "$real" == "/"* ]]; then
-    echo "ERROR: $real is not in $files_dir"
-    exit 1
-  fi
+    real=$(realpath -s --relative-base $files_dir "$fn")
+    if [[ "$real" == "."* || "$real" == ".."* || "$real" == "/"* ]]; then
+        echo "ERROR: $real is not in $files_dir"
+        exit 1
+    fi
 
-  files="$files $real"
+    files="$files $real"
 done
 
 # if some files were skipped, this is because they are data files that
 # might be on the devel PC, then print a message on how to override 
 # skipping of files
 if [ "$skipped" = "yes" ]; then
-  echo "INFO: some files were skipped, override with -f"
-  echo
+    echo "INFO: some files were skipped, override with -f"
+    echo
 fi
 
 # if there are no files to transfer then exit
 if [ -z "$files" ]; then
-  echo "ERROR: no files to transfer"
-  exit 1
+    echo "ERROR: no files to transfer"
+    exit 1
 fi
 
 # create tar file, containing the files to transfer to Android device
 cd $files_dir
 tar -cf /tmp/ezput.tar  $files
 if [ $? -ne 0 ]; then
-  echo "ERROR: failed to create /tmp/ezput.tar"
-  rm -f /tmp/ezput.tar
-  exit 1
+    echo "ERROR: failed to create /tmp/ezput.tar"
+    rm -f /tmp/ezput.tar
+    exit 1
 fi
 
 # copy the tar file to Android device
 ezsh -d $dev -p $password -q "put /tmp/ezput.tar"
 if [ $? -ne 0 ]; then 
-  echo "ERROR: failed to copy /tmp/ezput.tar to Android device"
-  rm -f /tmp/ezput.tar
-  exit 1
+    echo "ERROR: failed to copy /tmp/ezput.tar to Android device"
+    rm -f /tmp/ezput.tar
+    exit 1
 fi
 
 # extract ezput.tar on the Android device
 ezsh -d $dev -p $password -q "tar -xvf ezput.tar"
 if [ $? -ne 0 ]; then 
-  echo "ERROR: failed to extract ezput.tar on Android device"
-  rm -f /tmp/ezput.tar
-  exit 1
+    echo "ERROR: failed to extract ezput.tar on Android device"
+    rm -f /tmp/ezput.tar
+    exit 1
 fi
 
 # cleanup
