updae ezput

diff --git a/bin/ezput b/bin/ezput
--- a/bin/ezput
+++ b/bin/ezput
@@ -1,27 +1,60 @@
 #!/bin/bash
 
-# Usage:
-# - this must be invoked from an app or svc directory
-# - with no args, the git tracked files in this directory are transferred to the Android device
-# - with args, the files specified in the args are transferred to the Android device
-#
-# - examples:
-#   - ezput dev password                    # sends git tracked files from this dir to android dev
-#   - ezput dev password apps/layout        # sends just the apps/layout file to android dev
-#   - ezput dev password apps/lib/lib.[ch]  # sends apps/lib/lib.[ch] to android dev
+# xxx comments
+# xxx examples
+# ezput
+# ezput .
+# ezput . ../lib ../layout
+# ezput -f .
 
-# verify current dir is in a git repo
-top=$(git rev-parse --show-toplevel)
-if [ $? -ne 0 ]; then
-  echo "ERROR: not in git repo"
+function okay_to_xfer()
+{
+  if [ "$force" = yes ]; then
+    return 0
+  fi
+
+  if [[ "$1" == *".png" || \
+        "$1" == *".json" || \
+        "$1" == *".dat" || \
+        "$1" == *".mp3" || \
+        "$1" == *"params" || \
+        "$1" == *"FreeMonoBold.ttf" || \
+        "$1" == *"credits" || \
+        "$1" == *"licenses" ]]; \
+  then
+    return 1
+  else
+    return 0
+  fi
+}
+
+# #############  MAIN  ################
+
+# determine the top of the files directory tree,
+# this works if CWD is one of the following directories, for example:
+# - /path_to_files/files
+# - /path_to_files/files/apps
+# - /path_to_files/files/apps/Template
+if [ $(basename "$PWD") = files ]; then
+  files_dir=$PWD
+elif [ $(basename "$(dirname "$PWD")") = files ]; then
+  files_dir=$(dirname $PWD)
+elif [ $(basename "$(dirname "$(dirname "$PWD")")") = files ]; then
+  files_dir=$(dirname $PWD)
+  files_dir=$(dirname $files_dir)
+else
+  echo "ERROR: $PWD must be in files directory tree"
   exit 1
 fi
 
-# get device and password from env
+# get device and developer password from optional env vars
 dev=$EZAPP_DEVICE
 password=$EZAPP_PASSWD
 
-# set dev and password if the -d or -p options are supplied
+# process options 
+# -d <dev>       : dev name (such as from /etc/hosts), or dev ipaddr
+# -p <password>  : devel password
+# -f             : force xfer of data files
 while true; do
   if [ "$1" = "-d" ]; then
     dev=$2
@@ -29,61 +62,83 @@ while true; do
   elif [ "$1" = "-p" ]; then
     password=$2
     shift 2
+  elif [ "$1" = "-f" ]; then
+    force=yes
+    shift 1
+  elif [[ "$1" == "-"* ]]; then
+    echo "ERROR: invalid option $1"
+    exit 1
   else
     break
   fi
 done
 
-# verify dev and password args are provided
+# verify dev and password have been provided,
+# either from env vars or the -d and -p options
 if [ "$dev" = "" -o "$password" = "" ]; then
   echo "ERROR: device and password are required"
   exit 1
 fi
 
-# verify parent directory is 'apps' or 'svcs'
-parent_dir=$(basename $(dirname $PWD))
-if [ "$parent_dir" != apps -a "$parent_dir" != svcs ]; then
-  echo "ERROR: parent_dir must be apps or svcs"
+# if no args then default to xfering the current directory
+if [ $# -eq 0 ]; then
+  echo "INFO: transferring files from $PWD to Android device"
+  echo
+  set -- "."
+fi
+
+# find candidtate files to xfer
+find_output=$(find $* ! -type d 2>/dev/null)
+if [ $? -ne 0 ]; then
+  echo "ERROR: failed to create files list"
   exit 1
 fi
 
-# determine the code directory containing the app or svc code
-this_dir="$(basename $PWD)"
-if [ "$parent_dir" = apps ]; then
-  code_dir="apps/$this_dir"
-else
-  code_dir="svcs/$this_dir"
-fi
+# loop over candidate file
+# - if file is not okay to xfer (because it is a data file such as steps.dat,
+#   that might be on devel PC), then skip that file
+# - get the real path of the file, relative to the files_dir
+# - add the real path to list of files that will be xfered
+for fn in $find_output; do
+  okay_to_xfer $fn
+  if [ $? -ne 0 ]; then
+    echo "SKIPPING: $fn"
+    skipped=yes
+    continue
+  fi
 
-# if files are specified in the caller args then 
-# - check that the file does not begin with '..' or '/'
-# endif
-for i in $*; do
-  if [[ "$i" == ".."* || "$i" == "/"* ]]; then
-    echo "ERROR: $i invalid filename"
+  real=$(realpath -s --relative-base $files_dir "$fn")
+  if [[ "$real" == "."* || "$real" == ".."* || "$real" == "/"* ]]; then
+    echo "ERROR: $real is not in $files_dir"
     exit 1
   fi
-  specified_files="$specified_files $i"
+
+  files="$files $real"
 done
 
-# copy files to Android dev
-cd ../..
-if [ "$specified_files" != "" ]; then
-  files="$specified_files"
-else
-  files="$(git ls-files $code_dir)"
-  if [ "$files" = "" ]; then
-    echo "ERROR: no files"
-    exit 1
-  fi
+# if some files were skipped, this is because they are data files that
+# might be on the devel PC, then print a message on how to override
+if [ "$skipped" = "yes" ]; then
+  echo "INFO: some files were skipped, override with -f"
+  echo
 fi
 
+# if there are no files to xfer then exit
+if [ -z "$files" ]; then
+  echo "ERROR: no files to transfer"
+  exit 1
+fi
+
+# create tar file, containing the files to xfer to Android device;
+# the tar file is created relative to files_dir
+cd $files_dir
 tar -cf /tmp/ezput.tar  $files
 if [ $? -ne 0 ]; then
   rm -f /tmp/ezput.tar
   exit 1
 fi
 
+# copy the tar file to Android device, and extract it
 echo "Creating files on Android device ..."
 ezsh -d $dev -p $password -q "put /tmp/ezput.tar"
 if [ $? -ne 0 ]; then 
@@ -101,5 +156,7 @@ if [ $? -ne 0 ]; then
   exit 1
 fi
 
+# cleanup
 rm -f /tmp/ezput.tar
 exit 0
+
