cont

diff --git a/bin/eztest b/bin/eztest
--- a/bin/eztest
+++ b/bin/eztest
@@ -8,10 +8,10 @@ function linux_build()
     LIB_PATH=$(pwd)/../linux/local/lib
     gcc -o /tmp/$APP_NAME $CFLAGS ../bin/src/eztest_linux_wrapper.c $SRCS \
         -I . -I ../linux/local/include \
-        -L ../linux/local/lib -lezApp_lib -lmp3lame -llodepng -lcJSON -lkissfft-float -lSDL3 -lSDL3_ttf -lSDL3_mixer -lm \
+        -L $LIB_PATH -lezApp_lib -lmp3lame -lcJSON -llodepng -lkissfft-float -lSDL3 -lSDL3_mixer -lSDL3_ttf -lm \
         -Wl,-rpath,$LIB_PATH
     if [ $? -ne 0 ]; then
-        echo ABORT
+        echo "ABORT: failed to build /tmp/$APP_NAME"
         exit 1
     fi
 }
@@ -20,7 +20,7 @@ function usage()
 {
 echo -e "\
 \n\
-This script builds or runs the app/svc in the current directory.\n\
+This script builds or runs the app or svc in the current directory.\n\
 \n\
 Usage: eztest <cmd>\n\
 - run_on_picoc, runp: run this app/svc using picoc\n\
@@ -33,7 +33,6 @@ Default cmd is run_on_picoc.\n\
 
 # ######## SCRIPT STARTS HERE ########
 # xxx indent all scripts 4 spaces
-# xxx add -h option
 
 # set APP_NAME variable
 APP_NAME=$(basename $(pwd))
@@ -98,9 +97,14 @@ fi
 # if run_on_picoc requested then run using picoc
 if [ "$CMD" = run_on_picoc ]; then
     LIB_PATH=$(pwd)/../linux/local/lib
-    gcc -o /tmp/picoc -D UNIX_HOST -O2 -g -Wall -Werror ../src/picoc/picoc.c \
+    gcc -o /tmp/picoc -D UNIX_HOST -O2 -g -Wall -Werror ../src/picoc/picoc.c ../src/picoc/picoc_ezApp.c \
         -L $LIB_PATH -lpicoc -lezApp_lib -lmp3lame -lcJSON -llodepng -lkissfft-float -lSDL3 -lSDL3_mixer -lSDL3_ttf -lm \
         -Wl,-rpath,$LIB_PATH
+    if [ $? -ne 0 ]; then
+        echo "ABORT: failed to build /tmp/picoc"
+        exit 1
+    fi
+
     cp ../bin/src/eztest_picoc_wrapper.c /tmp
     sed -i -e "s=PROGNAME=$APP_NAME=" -e "s=DATA_DIR=$PARENT_DIR/$APP_NAME=" /tmp/eztest_picoc_wrapper.c
     # the { } syntax preserves the exception message generated by the shell if crash occurs
