cont

diff --git a/bin/eztest b/bin/eztest
--- a/bin/eztest
+++ b/bin/eztest
@@ -6,12 +6,8 @@ if [ "$CMD" = "" ]; then
     CMD=picoc
 fi
 
-# get CMD and validate
-if [ "$CMD" != build -a "$CMD" != linux -a "$CMD" != picoc ]; then
-    echo "ERROR: expected: build, linux, or picoc"
-    echo "ERROR: default is picoc"
-    exit 1
-fi
+# set APP_NAME variable
+APP_NAME=$(basename $(pwd))
 
 # verify parent directory is 'apps' or 'svcs'
 PARENT_DIR=$(basename $(dirname $PWD))
@@ -20,34 +16,48 @@ if [ "$PARENT_DIR" != apps -a "$PARENT_DIR" != svcs ]; then
     exit 1
 fi
 
-# set variables
-APP_DIR=$(basename $(pwd))
+# print action
+if [ "$CMD" == build ]; then
+    echo "Performing linux build of $APP_NAME ..."
+elif [ "$CMD" == run ]; then
+    echo "Performing linux build and run of $APP_NAME ..."
+elif [ "$CMD" == picoc ]; then
+    echo "Performing picoc run of $APP_NAME ..."
+else
+    echo "ERROR: expected: build, run, or picoc"
+    echo "ERROR: default is picoc"
+    exit 1
+fi
+echo
 
-# xxx -Wno-format-truncation ?
-APP_NAME=$APP_DIR
+# set CFLAGS, which is used when doing test build or test run on linux
 CFLAGS="-Wall -Werror -Wno-unused-result -Wno-format-truncation -fcommon -g -I. "
 
 # build and run is performed from the 'files' dir
 cd ../..
 
 # get list of src files, relative to the 'files' dir
-SRCS=$(echo $PARENT_DIR/$APP_DIR/*.c)
+SRCS=$(echo $PARENT_DIR/$APP_NAME/*.c)
 
-# debug
+# debug prints
 #echo "PARENT_DIR  = $PARENT_DIR"
-#echo "APP_DIR     = $APP_DIR"
 #echo "APP_NAME    = $APP_NAME"
 #echo "SRCS        = $SRCS"
 #echo "CFLAGS      = $CFLAGS"
 
+# ensure the key libraries are built;
+# note that this does not build all libraries,
+# libraries which would need to be manually built (if changed) are:
+# cJSON lodepng mp3lame SDL SDL_mixer SDL_ttf
 set -x
-make -C ../linux ezapp_lib picoc
+#xxx restore this: make -C ../linux ezapp_lib picoc
+make -C ../linux ezapp_lib
 if [ $? -ne 0 ]; then
     echo ABORT
     exit 1
 fi
 
-# perform command
+# perform requested command
 if [ "$CMD" = build ]; then
     gcc -DLINUX -o /tmp/$APP_NAME $CFLAGS $SRCS \
         -I ../linux/local/include \
@@ -56,7 +66,7 @@ if [ "$CMD" = build ]; then
         echo ABORT
         exit 1
     fi
-elif [ "$CMD" = linux ]; then
+elif [ "$CMD" = run ]; then
     gcc -DLINUX -o /tmp/$APP_NAME $CFLAGS $SRCS \
         -I ../linux/local/include \
         -L ../linux/local/lib -lezapp_lib -lmp3lame -llodepng -lcJSON -lSDL3 -lSDL3_ttf -lSDL3_mixer -lm \
@@ -65,13 +75,16 @@ elif [ "$CMD" = linux ]; then
         echo ABORT
         exit 1
     fi
-    exec -a $APP_NAME /tmp/$APP_NAME $PARENT_DIR/$APP_DIR
+    # the { } syntax preserves the exception message generated by the shell when the app crashes
+    { /tmp/$APP_NAME $PARENT_DIR/$APP_NAME; } |& ezlogfilter
+
 elif [ "$CMD" = picoc ]; then
     LIB_PATH=$(pwd)/../linux/local/lib
     gcc -o /tmp/picoc -D UNIX_HOST -O2 -g -Wall ../src/picoc/picoc.c \
         -L $LIB_PATH -lpicoc -lezapp_lib -lmp3lame -lcJSON -llodepng -lSDL3 -lSDL3_mixer -lSDL3_ttf -lm \
         -Wl,-rpath,$LIB_PATH
-    /tmp/picoc -n $APP_NAME $SRCS - $PARENT_DIR/$APP_DIR
+    # the { } syntax preserves the exception message generated by the shell when the app crashes
+    { /tmp/picoc -n $APP_NAME $SRCS - $PARENT_DIR/$APP_NAME; } |& ezlogfilter
     if [ $? -ne 0 ]; then
         echo ABORT
         exit 1
